# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-directive-colons
    stages: ["pre-commit"]
  - id: rst-backticks
    stages: ["pre-commit"]
